### ISSUE TITLE
Unknown Type Name `idtype_t`

### ISSUE THREAD

**Issue by athola** [newnix/nxes#1]
When installing using `make YACC=byacc ADDCFLAGS="-D_DEFAULT_SOURCE -D_POSIX_SOURCE=200809L -std=c99`, an error is encountered in `/usr/include/x86_64-linux-gnu/sys/wait.h:121:20` - `error: unknown type name 'idtype_t'` for `extern int waitid (idtype_t __idtype, __id_t __id, siginfo_t *__infop,`.

**Comment by newnix** [comment]
This is a known issue on Ubuntu, while `idtype_t` is defined on that platform, it's not yet clear exactly what macros are needed to expose the definition. Using a distribution based on musl libc instead of glibc appears not to have this issue though, so it should be easy enough to start looking for the differences.

**Comment by athola** [comment]
@newnix requesting collaboration on this project to add branch fixing linux compilation

**Comment by athola** [comment]
@newnix this issue can be closed with https://github.com/newnix/nxes/pull/3
